server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://124.223.187.213:3307/testdb?serverTimezone=UTC&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    timeout: 10000
    host: 124.223.187.213
    port: 16379
    password: #默认无密码
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.company.dao: debug